Имеются данные adult.csv (см. в материалах к занятию).
Целевой переменной является уровень дохода income (крайний правый столбец).
Описание признаков можно найти по ссылке http://www.cs.toronto.edu/~delve/data/adult/adultDetail.html
Вам необходимо построить модели логистической регрессии и SVM, которые предсказывает уровень дохода человека.
Вывести качество полученных моделей на тестовой выборке, используя функцию score у модели.
Готовый ноутбук выложить на гитхаб и прислать ссылку.


In [1]:
import pandas as pd
data = pd.read_csv('../adult.csv')
data

age     workclass  fnlwgt     education  educational-num  \
0       25       Private  226802          11th                7   
1       38       Private   89814       HS-grad                9   
2       28     Local-gov  336951    Assoc-acdm               12   
3       44       Private  160323  Some-college               10   
4       18             ?  103497  Some-college               10   
...    ...           ...     ...           ...              ...   
48837   27       Private  257302    Assoc-acdm               12   
48838   40       Private  154374       HS-grad                9   
48839   58       Private  151910       HS-grad                9   
48840   22       Private  201490       HS-grad                9   
48841   52  Self-emp-inc  287927       HS-grad                9   

           marital-status         occupation relationship   race  gender  \
0           Never-married  Machine-op-inspct    Own-child  Black    Male   
1      Married-civ-spouse    Farming-fishing      Husband  White    Male   
2      Married-civ-spouse    Protective-serv      Husband  White    Male   
3      Married-civ-spouse  Machine-op-inspct      Husband  Black    Male   
4           Never-married                  ?    Own-child  White  Female   
...                   ...                ...          ...    ...     ...   
48837  Married-civ-spouse       Tech-support         Wife  White  Female   
48838  Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
48839             Widowed       Adm-clerical    Unmarried  White  Female   
48840       Never-married       Adm-clerical    Own-child  White    Male   
48841  Married-civ-spouse    Exec-managerial         Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income  
0                 0             0              40  United-States  <=50K  
1                 0             0              50  United-States  <=50K  
2                 0             0              40  United-States   >50K  
3              7688             0              40  United-States   >50K  
4                 0             0              30  United-States  <=50K  
...             ...           ...             ...            ...    ...  
48837             0             0              38  United-States  <=50K  
48838             0             0              40  United-States   >50K  
48839             0             0              40  United-States  <=50K  
48840             0             0              20  United-States  <=50K  
48841         15024             0              40  United-States   >50K  

[48842 rows x 15 columns]

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


In [3]:
data.groupby(['income'])['income'].count()

income
<=50K    37155
>50K     11687
Name: income, dtype: int64

In [4]:
from sklearn.linear_model import LogisticRegression

In [5]:
data['income'].unique()

array(['<=50K', '>50K'], dtype=object)

In [6]:
sel = data[['age', 'education', 'income']]

X = pd.get_dummies (sel, columns = ['education'])
X

age income  education_10th  education_11th  education_12th  \
0       25  <=50K               0               1               0   
1       38  <=50K               0               0               0   
2       28   >50K               0               0               0   
3       44   >50K               0               0               0   
4       18  <=50K               0               0               0   
...    ...    ...             ...             ...             ...   
48837   27  <=50K               0               0               0   
48838   40   >50K               0               0               0   
48839   58  <=50K               0               0               0   
48840   22  <=50K               0               0               0   
48841   52   >50K               0               0               0   

       education_1st-4th  education_5th-6th  education_7th-8th  education_9th  \
0                      0                  0                  0              0   
1                      0                  0                  0              0   
2                      0                  0                  0              0   
3                      0                  0                  0              0   
4                      0                  0                  0              0   
...                  ...                ...                ...            ...   
48837                  0                  0                  0              0   
48838                  0                  0                  0              0   
48839                  0                  0                  0              0   
48840                  0                  0                  0              0   
48841                  0                  0                  0              0   

       education_Assoc-acdm  education_Assoc-voc  education_Bachelors  \
0                         0                    0                    0   
1                         0                    0                    0   
2                         1                    0                    0   
3                         0                    0                    0   
4                         0                    0                    0   
...                     ...                  ...                  ...   
48837                     1                    0                    0   
48838                     0                    0                    0   
48839                     0                    0                    0   
48840                     0                    0                    0   
48841                     0                    0                    0   

       education_Doctorate  education_HS-grad  education_Masters  \
0                        0                  0                  0   
1                        0                  1                  0   
2                        0                  0                  0   
3                        0                  0                  0   
4                        0                  0                  0   
...                    ...                ...                ...   
48837                    0                  0                  0   
48838                    0                  1                  0   
48839                    0                  1                  0   
48840                    0                  1                  0   
48841                    0                  1                  0   

       education_Preschool  education_Prof-school  education_Some-college  
0                        0                      0                       0  
1                        0                      0                       0  
2                        0                      0                       0  
3                        0                      0                       1  
4                        0                      0                       1  
...                    ...                    ...      

In [7]:
del X['income']

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

le.fit( data['income'])

LabelEncoder()

In [9]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [10]:
y = pd.Series (data = le.transform(data['income']))
y

0        0
1        0
2        1
3        1
4        0
        ..
48837    0
48838    1
48839    0
48840    0
48841    1
Length: 48842, dtype: int32

In [11]:
from sklearn.pipeline import make_pipeline # используем пайплайны для удобства
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 

model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000))

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
model.fit(X_train, y_train)
predictions = model.predict(X_test)

In [14]:
predictions[:5]

array([0, 0, 0, 0, 0])

In [15]:
import numpy as np

p = model.predict(X_test)

unique, counts = np.unique(p, return_counts=True)
print(unique, counts)

# 14 653

[0 1] [13117  1536]


In [16]:
model.predict_proba(X_test)

array([[0.73799022, 0.26200978],
       [0.91329479, 0.08670521],
       [0.54328862, 0.45671138],
       ...,
       [0.80652523, 0.19347477],
       [0.69483196, 0.30516804],
       [0.76191251, 0.23808749]])

In [17]:
model.score(X_train, y_train) 

0.7813916756851619

In [18]:
model.score(X_test,y_test)

0.7868013376100457

In [19]:
from sklearn.svm import SVC

In [20]:
clf = make_pipeline(StandardScaler(), SVC(gamma='auto')) 
clf.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [21]:
clf.score(X_train, y_train) 

0.7916288864839568

In [22]:
clf.score(X_test, y_test)

0.7945813144066062

In [25]:
p = clf.predict(X_test)

In [26]:
p

array([0, 0, 1, ..., 0, 0, 0])

In [27]:
unique, counts = np.unique(p, return_counts=True)
print(unique, counts)

[0 1] [12357  2296]
