In [4]:

from numpy import array
from numpy import mean
M = array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(M)
col_mean = mean(M, axis=0)
print(col_mean)
row_mean = mean(M, axis=1)
print(row_mean)


[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[1. 2. 3. 4. 5. 6.]
[3.5 3.5]


In [5]:

M = array([[1,2,3,4,5,6],[1,2,3,4,5,6],[2,2,3,4,5,6]])
col_mean = mean(M, axis=0)
print(col_mean)

[1.33333333 2.         3.         4.         5.         6.        ]


In [2]:
from numpy import mean
v = array([1,2,3,4,5,6])
print(v)
result = mean(v)
print(result)

[1 2 3 4 5 6]
3.5


In [7]:
print(4**2)

16
